on:
  push:
    branches: web
    paths:
      - index.qmd

name: Render and Publish

permissions:
   contents: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        
      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - uses: r-lib/actions/setup-r@v2
        with: 
          r-version: '4.2.0' # The R version to download (if necessary) and use.

      - name: Install dependencies
        run: |
          install.packages(c("rmarkdown"))
        shell: Rscript {0}


      - name: Render Book project
        run: quarto render index.qmd

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: docs # The folder the action should deploy.